-- MySQL Script generated by MySQL Workbench
-- Sat Nov 30 23:24:09 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

/* SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0; */
/* SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0; */
/* SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION'; */

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
USE master
CREATE DATABASE [Canteen]
GO
USE Canteen 

-- Table ACcount --
CREATE TABLE Account
(
	UserName VARCHAR(100) PRIMARY KEY,	
	DisplayName NVARCHAR(100) NOT NULL DEFAULT N'User',
	PassWord VARCHAR(1000) NOT NULL DEFAULT 0,
	AccType INT NOT NULL  DEFAULT 0 -- 1: admin && 0: staff
)
GO

-- -----------------------------------------------------
-- Table `mydb`.`NhanVien`
-- -----------------------------------------------------
CREATE TABLE NhanVien (
  [idNhanVien] INT NOT NULL IDENTITY(1,1),
  [HoTen] NVARCHAR(45) NULL,
  [NgaySinh] DATETIME2(0) NULL,
  PRIMARY KEY ([idNhanVien]))
;


-- -----------------------------------------------------
-- Table `mydb`.`MonAn`
-- -----------------------------------------------------
CREATE TABLE MonAn (
  [idMonAn] INT NOT NULL IDENTITY(1,1),
  [Ten] NVARCHAR(45) NULL,
  [Gia] INT CHECK ([Gia] > 0) NULL,
  [idLoaiMonAn] INT NOT NULL,
  [MieuTa] NVARCHAR(45) NULL,
  PRIMARY KEY ([idMonAn]))
;


-- -----------------------------------------------------
-- Table `mydb`.`HoaDon`
-- -----------------------------------------------------
CREATE TABLE HoaDon (
  [idHoaDon] INT NOT NULL IDENTITY(1,1),
  [NgayLap] DATETIME2(0) NULL,
  [TongTien] INT NULL,
  [NhanVien_idNhanVien] INT NOT NULL,
  PRIMARY KEY ([idHoaDon]),
  CONSTRAINT [fk_HoaDon_NhanVien1]
    FOREIGN KEY ([NhanVien_idNhanVien])
    REFERENCES NhanVien ([idNhanVien])
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
;

CREATE INDEX fk_HoaDon_NhanVien1_idx ON HoaDon ([NhanVien_idNhanVien] ASC);

-- -----------------------------------------------------
-- Table `mydb`.`ChiTietHoaDon`
-- -----------------------------------------------------
--CREATE TABLE ChiTietHoaDon (
--  [HoaDon_idHoaDon] INT NOT NULL,
--  [MonAn_idMonAn] INT NOT NULL,
--  [SoLuong] INT CHECK ([SoLuong] > 0) NULL,
--  PRIMARY KEY ([HoaDon_idHoaDon], [MonAn_idMonAn]),
--  CONSTRAINT [fk_HoaDon_has_MonAn_HoaDon1]
--    FOREIGN KEY ([HoaDon_idHoaDon])
--    REFERENCES HoaDon ([idHoaDon])
--    ON DELETE NO ACTION
--    ON UPDATE NO ACTION,
--  CONSTRAINT [fk_HoaDon_has_MonAn_MonAn1]
--    FOREIGN KEY ([MonAn_idMonAn])
--    REFERENCES MonAn ([idMonAn])
--    ON DELETE NO ACTION
--    ON UPDATE NO ACTION)
--;

--EDIT481
CREATE TABLE ChiTietHoaDon (
  [HoaDon_idHoaDon] INT NOT NULL,
  [MonAn_idMonAn] INT NOT NULL,
  [SoLuong] INT CHECK ([SoLuong] > 0) NULL,
  PRIMARY KEY ([HoaDon_idHoaDon], [MonAn_idMonAn]),
  CONSTRAINT [fk_HoaDon_has_MonAn_HoaDon1]
    FOREIGN KEY ([HoaDon_idHoaDon])
    REFERENCES HoaDon ([idHoaDon]),
  CONSTRAINT [fk_HoaDon_has_MonAn_MonAn1]
    FOREIGN KEY ([MonAn_idMonAn])
    REFERENCES MonAn ([idMonAn])
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
;

CREATE INDEX fk_HoaDon_has_MonAn_MonAn1_idx ON ChiTietHoaDon ([MonAn_idMonAn] ASC);

CREATE INDEX fk_HoaDon_has_MonAn_HoaDon1_idx ON ChiTietHoaDon ([HoaDon_idHoaDon] ASC);


-- -----------------------------------------------------
-- Table `mydb`.`LoaiMonAn`
-- -----------------------------------------------------
CREATE TABLE LoaiMonAn (
  [idLoaiMonAn] INT NOT NULL IDENTITY(1,1),
  [Ten_loai] NVARCHAR(45) NULL,
  PRIMARY KEY ([idLoaiMonAn]))
;


-- -----------------------------------------------------
-- Table `mydb`.`MonAn_thuoc_LoaiMon_`
-- -----------------------------------------------------
CREATE TABLE MonAn_thuoc_LoaiMon (
  [LoaiMonAn_idLoaiMonAn] INT NOT NULL,
  [MonAn_idMonAn] INT NOT NULL,
  PRIMARY KEY ([LoaiMonAn_idLoaiMonAn], [MonAn_idMonAn]),
  CONSTRAINT [fk_LoaiMonAn_has_MonAn_LoaiMonAn1]
    FOREIGN KEY ([LoaiMonAn_idLoaiMonAn])
    REFERENCES LoaiMonAn ([idLoaiMonAn])
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT [fk_LoaiMonAn_has_MonAn_MonAn1]
    FOREIGN KEY ([MonAn_idMonAn])
    REFERENCES MonAn ([idMonAn])
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
;

CREATE INDEX fk_LoaiMonAn_has_MonAn_MonAn1_idx ON MonAn_thuoc_LoaiMon ([MonAn_idMonAn] ASC);

CREATE INDEX fk_LoaiMonAn_has_MonAn_LoaiMonAn1_idx ON MonAn_thuoc_LoaiMon ([LoaiMonAn_idLoaiMonAn] ASC);


/* SET SQL_MODE=@OLD_SQL_MODE; */
/* SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS; */
/* SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS; */